name:                sarah
version:             0.1.0.0
github:              "bmabsout/excelator"
license:             BSD3
author:              "Bassel Mabsout"
maintainer:          "bmabsout@hotmail.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sarah#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- cassava
- vector
- text
- bytestring
- regex-applicative
- utf8-string
- validation
- xlsx
- containers
- ansi-terminal
- filepath
- foundation
- basement
- fsnotify
- fuzzyset
- generic-deriving

library:
  source-dirs: src

executables:
  sarah-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - sarah
